extends: eslint-config-airbnb
parser: babel-eslint

env:
  es6: true
  node: true
  mocha: true
  browser: true

rules:
  semi:
    - warn
    - never
  arrow-body-style:
    - error
    - as-needed
  no-param-reassign:
    - error
    - props: false
  react/prop-types: off
  no-mixed-operators: off

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
